exports.composersListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composers Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Composers List
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>Period</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
        <tr>
            <td>${slist[i].id}</td>
            <td>
                <a href="/compositores/${slist[i].id}">
                    ${slist[i].nome}
                </a>
            </td>
            <td>
                <a href="/compositores?periodo=${slist[i].periodo}">
                    ${slist[i].periodo}
                </a>
            </td>
            <td>
                [<a href="/compositores/edit/${slist[i].id}">Edit</a>][<a href="/compositores/delete/${slist[i].id}">Delete</a>]
            </td>
        </tr>
         `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by RPCW2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.composersFormPage = function(newId, d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" value="${newId}" readonly/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio" required/>
                        <label>Data Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" required/>
                        <label>Data Obito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" required/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo" required/>
                    </fieldset> 
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.composersPeriodPage = function(composers, periodo, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composers from ${periodo}</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Composers from ${periodo}</h1>
                </header>
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>Period</th>
                        </tr>
    `;
    composers.forEach(composer => {
        pagHTML += `
                <tr>
                    <td>${composer.id}</td>
                    <td>${composer.nome}</td>
                    <td>${composer.periodo}</td>
                </tr>
        `;
    });
    pagHTML += `
                    </table>
                </div>
                <footer class="w3-container w3-teal">
                    <address><a href="/">Voltar</a></address>
                </footer>
            </div>
        </body>
    </html>
    `;
    return pagHTML;
}

exports.composerFormEditPage = function(c, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" value="${c.id}" readonly/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${c.nome}"/>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${c.bio}"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" pattern="\d{4}-\d{2}-\d{2}" name="dataNasc" value="${c.dataNasc}"/>
                        <label>Data de Obito</label>
                        <input class="w3-input w3-round" type="date" pattern="\d{4}-\d{2}-\d{2}" name="dataObito" value="${c.dataObito}"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${c.periodo}"/>`
        
    pagHTML += `
                        </fieldset>  
                        <br/>
                        <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                    </form>
    
                    <footer class="w3-container w3-purple">
                        <h5>Generated by EngWeb2023 in ${c} - [<a href="/">Return</a>]</h5>
                    </footer>
                
                </div>
        `
    return pagHTML
}

// ---------------Composers's Page--------------------------------
// Change and adapt to current dataset...
exports.composersPage = function( composer, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Aluno: ${composer.Id}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${composer.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${composer.nome}</li>
                    <li><b>Número: </b> ${composer.id}</li>
                    <li><b>Data de Nascimento: </b> ${composer.dataNasc}</li>
                    <li><b>Data de Obito: </b> ${composer.dataObito}</li>
                    <li><b>Periodo: </b> <a>${composer.periodo}</a></li>
                    <li><b>Biografia: </b> <a>${composer.bio}</a></li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
            <footer class="w3-container w3-teal">
                <address><a href="/">Voltar</a></address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

//--------------- Periods --------------------------------------

exports.periodsListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periods Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Periods List
                    <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>Composers</th>
                            <th>Actions</th>
                        </tr>
                `
                for(let i=0; i < slist.length ; i++){
                    pagHTML += `
                    <tr>
                        <td>${slist[i].id}</td>
                        <td>
                            <a href="/periodos/${slist[i].id}">
                                ${slist[i].nome}
                            </a>
                        </td>
                        <td>
                            <a href="/compositores?periodo=${slist[i].nome}">
                                ${slist[i].numeroCompositores}
                            </a>
                        </td>
                        <td>
                            [<a href="/periodos/edit/${slist[i].id}">Edit</a>][<a href="/periodos/delete/${slist[i].id}">Delete</a>]
                        </td>
                    </tr>
                     `
                }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by RPCW2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodsPage = function(period, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Aluno: ${period.Id}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${period.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${period.nome}</li>
                    <li><b>Número: </b> ${period.id}</li>
                    <li><b>Nº de Compositores: </b> ${period.numeroCompositores}</li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
            <footer class="w3-container w3-teal">
                <address><a href="/periodos">Voltar</a></address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

exports.periodsFormPage = function(newId, d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Period Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Period Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" value="${newId}" readonly/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="numeroCompositores" value="${0}" required/>
                    </fieldset> 
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.periodFormEditPage = function(p, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Period Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Period Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" value="${p.id}" readonly/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${p.nome}"/>
                        <label>Numero de Compositores</label>
                        <input class="w3-input w3-round" type="text" name="numeroCompositores" value="${p.numeroCompositores}"/>`
        
    pagHTML += `
                        </fieldset>  
                        <br/>
                        <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                    </form>
    
                    <footer class="w3-container w3-purple">
                        <h5>Generated by EngWeb2023 in ${p} - [<a href="/periodos">Return</a>]</h5>
                    </footer>
                
                </div>
        `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}